### ISSUE TITLE
Release v0.6.7?

### ISSUE THREAD

**Issue by fmauch** [ros-melodic-arch/ros-melodic-tf2-tools#2]
We currently have v0.6.5 released as it is [released to the buildfarm](https://github.com/ros/rosdistro/blob/master/melodic/distribution.yaml#L3532). However, this version contains a python2 `print msg` statement in the script [`echo.py`](https://github.com/ros/geometry2/blob/0.6.5/tf2_tools/scripts/echo.py#L197).

This has been fixed one [commit](https://github.com/ros/geometry2/commit/62363ddf6c9feeea95c8b2f917559fadcb0e1034#diff-2ce440c30c0ea1ca07497d65ad0b2bd23f496b0d9da3de350ff005dcfb36b7d6) after releasing v0.6.5.

After that there have been the tags 0.6.6 and 0.6.7 on the `melodic-devel` branch, but they seem to never have been released to the buildfarm. Should we release v0.6.7 for all geometry2 packages (I think, it only makes sense to release all geometry2 packages in the same version)? Otherwise we would have to patch the `echo.py` script in order to make it work.

**Comment by bionade24** [comment]
I guess they decided later on that they'll be noetic-only. Or they forgot. I looked shortly in the commits between v0.6.5 and 6.6 and there's nothing breaking, so at least this one should be ok.

**Comment by fmauch** [comment]
I've updated to 0.6.6
